name: Generate AI Match Summary and Commit

on:
  workflow_dispatch:
    inputs:
      match_id:
        description: 'Football Match ID for which to generate and commit summary'
        required: true
        type: string

permissions:
  models: read
  contents: write # Required to push changes back to the repository

jobs:
  generate_commit_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run AI Summary Script and Capture Output
        id: ai_summary_script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_MODELS }}
        run: |
          echo "Running script with match_id: ${{ inputs.match_id }}"
          # Aja skripti ja ohjaa sen tuotos tiedostoon
          node scripts/generate-summary-with-sdk.js ${{ inputs.match_id }} > summary_output.txt
          echo "Script execution finished."
          echo "--- Script Output (summary_output.txt) ---"
          cat summary_output.txt
          echo "--- End of Script Output ---"
          # Poimi vain tekoälyn vastaus ja aseta se output-muuttujaan
          SUMMARY_CONTENT=$(grep -A 1000 "--- AI Generated Summary ---" summary_output.txt | tail -n +2)
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Commit analysis file
        run: |
          AI_SUMMARY="${{ steps.ai_summary_script.outputs.summary }}"
          if [ -z "$AI_SUMMARY" ]; then
            echo "AI summary is empty. Skipping commit."
            exit 0
          fi

          MATCH_ID="${{ inputs.match_id }}"
          FILE_PATH="analyses/MATCH_${MATCH_ID}.txt"

          mkdir -p analyses
          echo "$AI_SUMMARY" > "$FILE_PATH"
          echo "AI Summary saved to $FILE_PATH"

          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          if git diff --quiet "$FILE_PATH"; then
            echo "No changes to commit for $FILE_PATH."
            exit 0
          fi

          git add "$FILE_PATH"
          git commit -m "feat: Add AI analysis for match $MATCH_ID"
          echo "Committing $FILE_PATH"
          git push
          echo "Pushed $FILE_PATH to repository."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
